### PR TITLE
Add initial proposal for gRPC moving to CNCF

### PR DESCRIPTION
**Pull request by caniszczyk**
Please check out this proposal @zinuga :)

### CODE REVIEW

**Comment by hsaliak** [comment]
This should actually be a process RFC - could this be renamed to P1?

**Comment by caniszczyk** [comment]
@hsaliak fixed, thanks, wasn't super familiar with how to do a gRFC

**Comment by hsaliak** [comment]
@caniszczyk no worries, neither are we to be honest. Figuring out how we can make this work best. Thanks for switching the naming.

**Comment by caniszczyk** [comment]
Added link to the mailing list discussion:
https://groups.google.com/forum/#!msg/grpc-io/AWCJlR-MA9k/N-EKJtQPAwAJ

**Comment by caniszczyk** [comment]
@zinuga I think you need to sign the Google CLA oddly enough :)

**Comment by zinuga** [comment]
Oops. Connected my corp account now with github, so now github knows I dont need to sign Google CLA.

**Comment by hsaliak** [comment]
Ping - could you please mark this as final and submit once the checks pass?

**Pull request merged**
