### PR TITLE
Clarify retry budgeting algorithm

### PR DESCRIPTION
**Pull request by lukaszx0**
Correct me if I'm wrong, but my understanding is that `token_count` should be incremented only if it's lower than `maxTokens`. Otherwise it'll grow indefinitely so if service will be stable for a day and generate 1M tokens, next day 1h outage won't trigger the algorithm.

cc @ericgribkoff @ncteisen @ejona86

### CODE REVIEW

**Comment by lukaszx0** [comment]
Actually, I think that same clarification is need for decrementing `token_count` - _decrement if token_count > 0_

**Comment by ncteisen** [comment]
Good catch! But rather than adding conditionals to the bullet points, how about we add a sentence like:

"the gRPC client maintains a `token_count` variable which is initially set to `maxTokens`, and is always clamped between 0 and `maxTokens`"

Do you think that is clear enough?

**Comment by lukaszx0** [comment]
@ncteisen reworded a bit, what do you think?

**Comment by lukaszx0** [comment]
:shipit:

**Comment by lukaszx0** [comment]
@ericgribkoff extracted whitespace fixes to separate commit.

:shipit: ?

**Comment by ericgribkoff** [comment]
Ah, sorry about that - I would have merged this as-is (the nit was surely overestimating the future value of an accurate blame on every line of this file...), but I didn't realize that the merge was waiting on me due to permissions. Thanks for the fix!

**Pull request merged**
