### PR TITLE
Update L74 implementation status

### PR DESCRIPTION
**Pull request by ejona86**

### CODE REVIEW

**Comment by ejona86** [comment]
@sanjaypujare, friendly ping (you can tell I forgot about this...)

**Comment by sanjaypujare** [comment]
I forgot too (since Nov 19,2020)! Will take a look ASAP

**Review by sanjaypujare — APPROVED** [review]
LGTM. Sorry for the delay

**Comment by ejona86** [comment]
@sanjaypujare, np. If it were important I'd obviously have pinged sooner :smile:

**Pull request merged**
