### PR TITLE
L13: gRPC Python Client and Server Interceptors

### PR DESCRIPTION
**Pull request by mehrdada**
Addresses https://github.com/grpc/grpc/issues/8767
Implementation: https://github.com/grpc/grpc/pull/12778
Discussion: https://groups.google.com/d/msg/grpc-io/7qIzyCPWbUA/1NKGXAQHCgAJ

### CODE REVIEW

**Comment by hsaliak** [comment]
@nathanielmanistaatgoogle please approve so that this proposal can be merged in a timely manner.

**Comment by mehrdada** [comment]
I need to make modifications to it. The API has somewhat changed.  Please hold off on reviewing it. I have not forgotten.

**Comment by naggie** [comment]
After following about 6 links in various PRs and issues around the same change, I'm confused about the status of this interceptor feature -- is it already in 1.8.x?

Thanks for the work on this feature, it will allow me to remove considerable boilerplate.

**Comment by mehrdada** [comment]
@naggie Yes, we pursued this proposal and captured some user feedback and an experimental version (which will very likely become final after marking this proposal as approved) is merged already and is ready to use. I still need to update this proposal to incorporate the feedback and update it to match the version that we shipped since 1.8.

**Comment by dfawley** [comment]
For consistency, please rename this file to `L13-python-...` before merging.  Thanks!

**Comment by lidizheng** [comment]
@mehrdada Can you take some time to update the server interceptor section to match the implementation? We want to make interceptor API stable, and it will be great to make this gRFC a reference of its rationale/design.

**Comment by mehrdada** [comment]
@lidizheng I don't think I am going to have any free time to spend on that, sorry. Feel free to fork it and make it your own; I don't mind.

**Pull request closed without merging**
