### PR TITLE
L15-PHP-Interceptors

### PR DESCRIPTION
**Pull request by ZhouyihaiDing**
Implementation: https://github.com/grpc/grpc/pull/13342

### CODE REVIEW

**Comment by ZhouyihaiDing** [comment]
Draft versions of this PR were reviewed at https://github.com/ZhouyihaiDing/proposal/pull/1 with @mehrdada

**Comment by hsaliak** [comment]
@mehrdada assigning you as reviewer since you are also iterating on the PR. -- what's the status of this?

@ZhouyihaiDing can you please start a discusson thread about this in grpc-io and update the PR with the discussion? Given that the PR is open, it would be good to make this go through the process and get it merged.

**Comment by mehrdada** [comment]
@ZhouyihaiDing Please add a commit to this PR (do not force push) and add the "Discussion Link" and "Last Updated" entries and set the status to "In Review". Thanks!

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Comment by thelinuxfoundation** [comment]
Thank you for your pull request. Before we can look at your contribution, we need to ensure all contributors are covered by a Contributor License Agreement.

After the following items are addressed, please respond with a new comment here, and the automated system will re-verify.

* One or more commits are not associated with a GitHub user. The email used in the Git commit must match a verified email address in a GitHub user profile. For more information, please see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

_Regards,
CLA GitHub bot_

**Pull request merged**
